### ISSUE TITLE
MCLink::libdir: The library directory does not exist.

### ISSUE THREAD

**Issue by wuyudi** [njpipeorgan/MathCompile#2]
I am on windows 10, mma 12.1 , mingw

I run
```mathematica
CCompilerDriver`$CCompiler = {"Compiler" -> 
    CCompilerDriver`GenericCCompiler`GenericCCompiler, 
   "CompilerInstallation" -> "C:\\MinGW\\bin", 
   "CompilerName" -> "g++.exe"};
```

and then I run

    $CCompiler

get

> {"Compiler" -> CCompilerDriver\`GenericCCompiler\`GenericCCompiler, 
 "CompilerInstallation" -> "C:\\MinGW\\bin", 
 "CompilerName" -> "g++.exe"}

then I tried one example:

    << MathCompile` (*导入包*)
    f = Function[{Typed[x, {Integer, 1}]}, 
    Times @@ x];(*定义一个函数*)compiled = CompileToBinary[f];(*编译成二进制*)

It returns that 

> MCLink::libdir: The library directory does not exist.

So how to fix it?

**Comment by njpipeorgan** [comment]
It is probably caused by missing output directory. You can try to create it manually by
```
CreateDirectory["TargetDirectory"/.Options[CCompilerDriver`CreateLibrary]]
```
then it should work fine. 

I will post a fix to this issue in the next release.
