### ISSUE TITLE
The newest version 0.2.4 doesn't support Mathematica 11.3

### ISSUE THREAD

**Issue by wuyudi** [njpipeorgan/MathCompile#3]
Though I know this isn't a problem. But since MMA 12.1's front end is [so slow](https://mathematica.stackexchange.com/questions/216746/user-interface-mathematica-12-1-terribly-slow). I have to go back to MMA 11.3. As a result , I can't use it.
![image](https://user-images.githubusercontent.com/30024051/79628982-214a7900-8135-11ea-995e-98459186d478.png)

**Comment by njpipeorgan** [comment]
I just add a new branch trying to add support for v11.3. You can remove the current package and install this new one: 

    PacletInstall["https://github.com/njpipeorgan/MathCompile/releases/download/v0.2.4/MathCompile-0.2.4.paclet"]

The problem of supporting versions prior to 12.0 is that NumericArray cannot be used for arguments and return values, but other features should work fine.

**Comment by wuyudi** [comment]
OK... I know the problem. At that time, I am using MinGW **32bit**, not **w64**, so mma didn't recognize it.

**Comment by njpipeorgan** [comment]
I see, thanks for letting me know.

Brian

**Comment by asukaminato0721** [comment]
Just some additional information.

It seems that the main problem is

https://reference.wolfram.com/language/ref/Typed.html?q=Typed

`Typed` is in 12.x or newer.

in the old version, RawArray can be used to replace NumericArray.

https://zhuanlan.zhihu.com/p/350280934
