### ISSUE TITLE
How to solve "The header file "math_compile.h" cannot be found"

### ISSUE THREAD

**Issue by renguangyu** [njpipeorgan/MathCompile#4]
After the tested codes, two errors occured to prevent the next application.
The first one was after 
`<< MathCompile` 
f = Function[{Typed[x, Integer]}, x + 2];
CompileToCode[f]   `
to find the information"_Import::nffil: File C:\Users\Administrator\AppData\Roaming\Mathematica\Applications\/SourceFiles/src_template.cpp not found during Import_."

When compiling to the binary,
`f = Function[{Typed[x, {Integer, 1}]}, Times @@ x];
compiled = CompileToBinary[f];`
the hint as "`MCLink::noheader: The header file "math_compile.h" cannot be found.`_" failed to get the binary codes.

------------------------
1. Did the problem bring out due to the g++ not installed properly?
I have tried to use both the TDM-GCC-64 and mingWx86_64-8.1.0-release-posix-sjlj-rt_v6-rev0 to fail.
2. Did MathCompile contrdict with Compile with the option "CompilationTarget -> "C""? After all, to compile to c you also need  like 
`<<CCompilerDriver`GenericCCompiler`
$CCompiler={"Compiler"->GenericCCompiler,"CompilerInstallation"->"C:\\TDM-GCC-64\\bin","CompilerName"->"gcc.exe","SystemCompileOptions"->"-Ofast"};`
-------------------------------------------
I appreciate your great work very much with large willing to try MathCompile.

**Comment by njpipeorgan** [comment]
It seems to me that MathCompile didn't correctly find its root directory, where src_template.cpp etc. were located. 

Which version of Mathematica were you running, and did you install MathCompile through PacletInstall?

You can try the following and let me know what the result is:
```
<<MathCompile`;
MathCompile`Private`$packagepath
```

**Comment by renguangyu** [comment]
I tried again in another machine to avoid some problem on networdconnection.
The version of MMA is 12.0.0.0.  This time I installed MathCompile through PacletInstall and executed the simple snippet to find none of warnings commented.
However, the outcomes like addone[5] just feedbacked meaningless
`In[202]:= addone[5]

Out[202]= "auto main_function(const int64_t& v46) {
     return wl::val(wl::plus(WL_PASS(v46), int64_t(1)));
 }
 "[5]`

--------------------------------
Besides, 
```
<<MathCompile`;
MathCompile`Private`$packagepath
```
seems normal to bring about
_"D:\\Mathematica\\12.0\\AddOns\\ExtraPackages\\MathCompile\\"_

**Comment by njpipeorgan** [comment]
To call the compiled function, you need to use `CompileToBinary`. I guess that was the problem.

**Comment by renguangyu** [comment]
When excuting CompileToBinary, I find two errors:
```
MCLink::genfail: Failed to generate the library.
MCCxx::error: Check $CompilerOutput for the errors.
```
How to solve them?

**Comment by njpipeorgan** [comment]
What's the value of `$CompilerOutput` right after you getting these errors?

If you are using sjlj exception handling, maybe that was the problem, as MathCompile only supports seh for exception handling. If you want to use GCC on Windows, you can check [this page](https://github.com/njpipeorgan/MathCompile/wiki/Prerequisites-for-C-Compiler) for how to install Mingw-w64

**Comment by renguangyu** [comment]
I passed through the CompileToBinary, though the process is weird a lot—— nonsense when firstly I executed the code "<<CCompilerDriverGenericCCompiler", but after I tried that again CompileToBinary was sucessful to use. 
However, the function CompileToBinary failed still. 

I tested a triple loop,  CompileToBinary is much faster than not compiled, but a little slower than original Compile to "c".
I would try win10 another time.
the basic codes for my test:
`
fn = Function[{n}, 
   Module[{x = Table[0., n], y = Table[0., n], z = Table[0., n]},
    	Do[x[[i]] = Sqrt[10.0 + x[[i - 1]]] + 1.0;
     		Do[y[[j]] = Sqrt[x[[i - 1]]] + y[[j - 1]];
      			Do[z[[k]] = y[[j]] + 0.95 x[[i]] + 0.9 z[[k - 1]],
       			{k, 2, n}]
      		, {j, 2, n}]
     	, {i, 2, n}]; Total@z]
   ];
`
Similar to Compile, if the decimals in codes were dropped,such as `{x = Table[0, n], y = Table[0, n], z = Table[0, n]}` , CompileToBinary was also with failure. I don't  know the reason.

**Comment by njpipeorgan** [comment]
You are correct. If you initialize `x` as array of integers, they cannot be assigned by doubles since they require narrowing conversions. 

It is certainly possible that the function you've given runs faster when using native `Compile` due to its structure (`Do` loops). I suspect that it may be due to some redundant checks on array boundaries etc. in MathCompile.
